### ISSUE TITLE
bug/validate-input

### ISSUE THREAD

**Issue by gbudau** [42AGV/webserv#104]
The HTTP request URL and the filename of POST upload are susceptible to [path traversal](https://owasp.org/www-community/attacks/Path_Traversal) exploits.

Example:
```shell
python
>>> import requests
>>> r = requests.get("http://localhost:8080/../../../../../../../../../../../../../../etc/passwd")
>>> print(r.text)
```

Possible fix:
Either disallow `/..` in the request URL and the filename of POST upload or simplify the paths.

**Comment by Damrod** [comment]
FYI: something they taught me in a security training. What happens if you just remove all '../' and the somebody does
r = requests.get("http://localhost:8080/..././..././..././..././..././..././..././etc/passwd") ?

On the other hand, although this is important in real life, to me it seems like a moderate overkill think about it in our project...
