### ISSUE TITLE
Wrong CGI return status

### ISSUE THREAD

**Issue by Damrod** [42AGV/webserv#124]
We only return error response from a CGI script when the CGI binary doesn't have execution permissions. If the binary is malformed or if any of the other system calls we do after the fork fail we will leave the client hanging without any response.

**Comment by Damrod** [comment]
Reading the output of the CGI program without waiting, would require buffering the output in our program, and as soon as sigchild for the particular program is received, handle the signal to set the status of the http response, to set the response to the right status.
But we cannot warrantee that we will not receive this signal as we are handling some syscall, which means that either:
1) the syscall that would be interrupted may be called from the beggining as our program resumes normal operation,
1) the syscall that would be interrupted may be returning -1, and set errno to EINTR.
Properly handling of this issue would require reading errno after each read/recv/write/send (which are some of the syscalls that may be interrupted by the ISR) syscalls, which is forbidden by the subject. So it was decided to not take any action on this topic.

**Comment by gbudau** [comment]
Maybe there is a solution to this problem that does not require `wait()`/`waitpid()`.

We could parse the CGI output (headers), and in case there is no output at all, our server should return status `500 Internal Server Error`.

From [RFC 3875](https://datatracker.ietf.org/doc/html/rfc3875#section-6) (6. CGI Response):

>    **A script MUST always provide a non-empty response**, and so there is a
   system-defined method for it to send this data back to the server.
   Unless defined otherwise, this will be via the 'standard output' file
   descriptor.

>  The script MUST check the REQUEST_METHOD variable when processing the
   request and preparing its response.

>   The server MAY implement a timeout period within which data must be
   received from the script.  If a server implementation defines such a
   timeout and receives no data from a script within the timeout period,
   the server MAY terminate the script process.

>    **The response comprises a message-header and a message-body, separated
   by a blank line.  The message-header contains one or more header
   fields.**  The body may be NULL.

> **The script MUST return a Content-Type header field.  A Status header
   field is optional, and status 200 'OK' is assumed if it is omitted.**
   The server MUST make any appropriate modifications to the script's
   output to ensure that the response to the client complies with the
   response protocol version.
